name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test -v ./...
  
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install Godoc
        run: go install golang.org/x/tools/cmd/godoc@latest

      - name: Generate Go Documentation
        run: |
          godoc -http=:6060 &
          sleep 5 # Give godoc server time to start
          wget -r -nH --cut-dirs=1 --no-parent --reject "index.html*" http://localhost:6060/pkg/github.com/erikkvale/yggdrasil/
          mkdir -p docs/godocs
          mv yggdrasil/* docs/godocs/
          rm -rf yggdrasil


      - name: Add Godoc to MkDocs
        run: |
          echo '- Go Documentation: godocs' >> mkdocs.yml

    needs: test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force

    needs: generate-docs
